name: build
on: 
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_ACTIONS: true

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-latest
    services:
      metastore:
        image: apache/hive:4.0.0-beta-2-SNAPSHOT
        env:
          SERVICE_NAME: metastore
          SERVICE_OPTS: "-Dhive.root.logger=console"
        ports:
          - 9083:9083
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install target
        uses: dtolnay/rust-toolchain@stable 
      - name: Build
        run: cargo build --verbose --release
      - name: Await metastore container
        run: ./metastore.sh await
      - name: Test
        run: cargo test -- --show-output
        env:
          RUST_LOG: trace
          RUSTFLAGS: '--cfg ci'
      - name: Archive binaries
        uses: actions/upload-artifact@v4
        with:
          name: nektar-x86_64
          path: |
            target/release/nektar

  build-aarch64-darwin:
    runs-on: 	macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install aarch64 target
        uses: dtolnay/rust-toolchain@stable 
        with:
          targets: aarch64-apple-darwin
      - name: Build
        run: cargo build --verbose --release --target=aarch64-apple-darwin
      - name: Archive binaries
        uses: actions/upload-artifact@v4
        with:
          name: nektar-aarch64-apple-darwin
          path: |
            target/aarch64-apple-darwin/release/nektar
